# NATS server 2 — TurboCable cluster node n2

server_name: n2
listen: 0.0.0.0:4222
http: 0.0.0.0:8222

jetstream {
  store_dir: /data/nats
  max_memory_store: 1GB
  max_file_store: 10GB
}

cluster {
  name: tc-cluster
  listen: 0.0.0.0:6222
  routes: [
    nats-route://nats1:6222,
    nats-route://nats3:6222
  ]
}

max_connections: 100000
max_payload: 1MB
